/*
 * This settings file was auto generated by the Gradle buildInit task
 * by 'mariusmerkevicius' at '10/18/15 7:14 PM' with Gradle 2.7
 *
 * The settings file is used to specify which projects to include in your build.
 * In a single project build this file can be empty or even removed.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user guide at https://docs.gradle.org/2.7/userguide/multi_project_builds.html
 */

rootProject.name = "wt4"
include(
        ":app",
        ":jira-client",
        ":remote",
        ":models",
        ":components",
        ":database2",
        ":mock-factory",
        ":package",
        ":credits"
)
