/*
 * This file is generated by jOOQ.
 */
package lt.markmerkk.schema1;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import lt.markmerkk.schema1.tables.SqliteSequence;
import lt.markmerkk.schema1.tables.Ticket;
import lt.markmerkk.schema1.tables.Worklog;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultSchema extends SchemaImpl {

    private static final long serialVersionUID = -235744202;

    /**
     * The reference instance of <code></code>
     */
    public static final DefaultSchema DEFAULT_SCHEMA = new DefaultSchema();

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public final SqliteSequence SQLITE_SEQUENCE = lt.markmerkk.schema1.tables.SqliteSequence.SQLITE_SEQUENCE;

    /**
     * The table <code>ticket</code>.
     */
    public final Ticket TICKET = lt.markmerkk.schema1.tables.Ticket.TICKET;

    /**
     * The table <code>worklog</code>.
     */
    public final Worklog WORKLOG = lt.markmerkk.schema1.tables.Worklog.WORKLOG;

    /**
     * No further instances allowed
     */
    private DefaultSchema() {
        super("", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            SqliteSequence.SQLITE_SEQUENCE,
            Ticket.TICKET,
            Worklog.WORKLOG);
    }
}
