/*
 * This file is generated by jOOQ.
 */
package lt.markmerkk.schema1;


import javax.annotation.Generated;

import lt.markmerkk.schema1.tables.SqliteSequence;
import lt.markmerkk.schema1.tables.Ticket;
import lt.markmerkk.schema1.tables.Worklog;


/**
 * Convenience access to all tables in 
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>sqlite_sequence</code>.
     */
    public static final SqliteSequence SQLITE_SEQUENCE = lt.markmerkk.schema1.tables.SqliteSequence.SQLITE_SEQUENCE;

    /**
     * The table <code>ticket</code>.
     */
    public static final Ticket TICKET = lt.markmerkk.schema1.tables.Ticket.TICKET;

    /**
     * The table <code>worklog</code>.
     */
    public static final Worklog WORKLOG = lt.markmerkk.schema1.tables.Worklog.WORKLOG;
}
