package lt.markmerkk

/**
 * @author mariusmerkevicius
 * @since 2016-08-14
 */
object GAStatics {
    val CATEGORY_BUTTON = "BUTTON"
    val CATEGORY_GENERIC = "GENERIC"
    val ACTION_ENTER = "ENTER_TIME"
    val ACTION_SYNC_MAIN = "SYNC_MAIN"
    val ACTION_SYNC_SETTINGS = "SYNC_SETTINGS"
    val ACTION_SEARCH_REFRESH = "SEARCH_REFRESH"
    val ACTION_START = "START"

    val VIEW_DAY = "VIEW_DAY"
    val VIEW_DAY_SIMPLE = "VIEW_SIMPLE_DAY"
    val VIEW_WEEK = "VIEW_SIMPLE_WEEK"
    val VIEW_CALENDAR_DAY = "VIEW_CALENDAR_DAY"
    val VIEW_CALENDAR_WEEK = "VIEW_CALENDAR_WEEK"
    val VIEW_GRAPH = "VIEW_GRAPH"
    val VIEW_SETTINGS = "VIEW_SETTINGS"
}