/*
 * This file is generated by jOOQ.
 */
package lt.markmerkk.schema1.tables.records;


import javax.annotation.Generated;

import lt.markmerkk.schema1.tables.TicketUseHistory;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TicketUseHistoryRecord extends UpdatableRecordImpl<TicketUseHistoryRecord> implements Record5<Integer, String, String, String, Long> {

    private static final long serialVersionUID = 1078975059;

    /**
     * Setter for <code>ticket_use_history.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>ticket_use_history.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>ticket_use_history.code_project</code>.
     */
    public void setCodeProject(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>ticket_use_history.code_project</code>.
     */
    public String getCodeProject() {
        return (String) get(1);
    }

    /**
     * Setter for <code>ticket_use_history.code_number</code>.
     */
    public void setCodeNumber(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>ticket_use_history.code_number</code>.
     */
    public String getCodeNumber() {
        return (String) get(2);
    }

    /**
     * Setter for <code>ticket_use_history.code</code>.
     */
    public void setCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>ticket_use_history.code</code>.
     */
    public String getCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>ticket_use_history.lastUsed</code>.
     */
    public void setLastused(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>ticket_use_history.lastUsed</code>.
     */
    public Long getLastused() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, String, String, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TicketUseHistory.TICKET_USE_HISTORY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TicketUseHistory.TICKET_USE_HISTORY.CODE_PROJECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return TicketUseHistory.TICKET_USE_HISTORY.CODE_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return TicketUseHistory.TICKET_USE_HISTORY.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return TicketUseHistory.TICKET_USE_HISTORY.LASTUSED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCodeProject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getCodeNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getLastused();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCodeProject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getCodeNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getLastused();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TicketUseHistoryRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TicketUseHistoryRecord value2(String value) {
        setCodeProject(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TicketUseHistoryRecord value3(String value) {
        setCodeNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TicketUseHistoryRecord value4(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TicketUseHistoryRecord value5(Long value) {
        setLastused(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TicketUseHistoryRecord values(Integer value1, String value2, String value3, String value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TicketUseHistoryRecord
     */
    public TicketUseHistoryRecord() {
        super(TicketUseHistory.TICKET_USE_HISTORY);
    }

    /**
     * Create a detached, initialised TicketUseHistoryRecord
     */
    public TicketUseHistoryRecord(Integer id, String codeProject, String codeNumber, String code, Long lastused) {
        super(TicketUseHistory.TICKET_USE_HISTORY);

        set(0, id);
        set(1, codeProject);
        set(2, codeNumber);
        set(3, code);
        set(4, lastused);
    }
}
