/*
 * This file is generated by jOOQ.
 */
package lt.markmerkk.schema1.tables.records;


import javax.annotation.Generated;

import lt.markmerkk.schema1.tables.Worklog;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WorklogRecord extends UpdatableRecordImpl<WorklogRecord> implements Record13<Integer, Long, Long, Long, String, String, Long, Byte, Byte, Byte, String, Long, String> {

    private static final long serialVersionUID = -1597722513;

    /**
     * Setter for <code>worklog.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>worklog.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>worklog.start</code>.
     */
    public void setStart(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>worklog.start</code>.
     */
    public Long getStart() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>worklog.end</code>.
     */
    public void setEnd(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>worklog.end</code>.
     */
    public Long getEnd() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>worklog.duration</code>.
     */
    public void setDuration(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>worklog.duration</code>.
     */
    public Long getDuration() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>worklog.code</code>.
     */
    public void setCode(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>worklog.code</code>.
     */
    public String getCode() {
        return (String) get(4);
    }

    /**
     * Setter for <code>worklog.comment</code>.
     */
    public void setComment(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>worklog.comment</code>.
     */
    public String getComment() {
        return (String) get(5);
    }

    /**
     * Setter for <code>worklog.remote_id</code>.
     */
    public void setRemoteId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>worklog.remote_id</code>.
     */
    public Long getRemoteId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>worklog.is_deleted</code>.
     */
    public void setIsDeleted(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>worklog.is_deleted</code>.
     */
    public Byte getIsDeleted() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>worklog.is_dirty</code>.
     */
    public void setIsDirty(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>worklog.is_dirty</code>.
     */
    public Byte getIsDirty() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>worklog.is_error</code>.
     */
    public void setIsError(Byte value) {
        set(9, value);
    }

    /**
     * Getter for <code>worklog.is_error</code>.
     */
    public Byte getIsError() {
        return (Byte) get(9);
    }

    /**
     * Setter for <code>worklog.error_message</code>.
     */
    public void setErrorMessage(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>worklog.error_message</code>.
     */
    public String getErrorMessage() {
        return (String) get(10);
    }

    /**
     * Setter for <code>worklog.fetchTime</code>.
     */
    public void setFetchtime(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>worklog.fetchTime</code>.
     */
    public Long getFetchtime() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>worklog.URL</code>.
     */
    public void setUrl(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>worklog.URL</code>.
     */
    public String getUrl() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Long, Long, Long, String, String, Long, Byte, Byte, Byte, String, Long, String> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, Long, Long, Long, String, String, Long, Byte, Byte, Byte, String, Long, String> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Worklog.WORKLOG.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Worklog.WORKLOG.START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field3() {
        return Worklog.WORKLOG.END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Worklog.WORKLOG.DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Worklog.WORKLOG.CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Worklog.WORKLOG.COMMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field7() {
        return Worklog.WORKLOG.REMOTE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return Worklog.WORKLOG.IS_DELETED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return Worklog.WORKLOG.IS_DIRTY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field10() {
        return Worklog.WORKLOG.IS_ERROR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Worklog.WORKLOG.ERROR_MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field12() {
        return Worklog.WORKLOG.FETCHTIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Worklog.WORKLOG.URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component2() {
        return getStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component3() {
        return getEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component7() {
        return getRemoteId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component8() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getIsDirty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component10() {
        return getIsError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getErrorMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component12() {
        return getFetchtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value3() {
        return getEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getComment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value7() {
        return getRemoteId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getIsDeleted();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getIsDirty();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value10() {
        return getIsError();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getErrorMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value12() {
        return getFetchtime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value2(Long value) {
        setStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value3(Long value) {
        setEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value4(Long value) {
        setDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value5(String value) {
        setCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value6(String value) {
        setComment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value7(Long value) {
        setRemoteId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value8(Byte value) {
        setIsDeleted(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value9(Byte value) {
        setIsDirty(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value10(Byte value) {
        setIsError(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value11(String value) {
        setErrorMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value12(Long value) {
        setFetchtime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord value13(String value) {
        setUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WorklogRecord values(Integer value1, Long value2, Long value3, Long value4, String value5, String value6, Long value7, Byte value8, Byte value9, Byte value10, String value11, Long value12, String value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WorklogRecord
     */
    public WorklogRecord() {
        super(Worklog.WORKLOG);
    }

    /**
     * Create a detached, initialised WorklogRecord
     */
    public WorklogRecord(Integer id, Long start, Long end, Long duration, String code, String comment, Long remoteId, Byte isDeleted, Byte isDirty, Byte isError, String errorMessage, Long fetchtime, String url) {
        super(Worklog.WORKLOG);

        set(0, id);
        set(1, start);
        set(2, end);
        set(3, duration);
        set(4, code);
        set(5, comment);
        set(6, remoteId);
        set(7, isDeleted);
        set(8, isDirty);
        set(9, isError);
        set(10, errorMessage);
        set(11, fetchtime);
        set(12, url);
    }
}
